name: Deployment
on:
  push:
    branches:
      - master
      - SIT
env:
  MONGODB_CLUSTER_ADDRESS: ${{ Secrets.MONGODB_CLUSTER_ADDRESS }}
  MONGODB_USERNAME: ${{ Secrets.MONGODB_USERNAME }}
  MONGODB_PASSWORD: ${{ Secrets.MONGODB_PASSWORD }}
  PORT: ${{ vars.PORT }}
jobs:
  test:
    name: Test Job 1
    runs-on: ubuntu-latest
    environment: testing
    env:
      PORT: ${{ env.PORT }}
      MONGODB_DB_NAME: "Main-Cluster"
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Printing Port
        run: |
          echo "http://127.0.0.1:$PORT"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "Printing the Output $PORT"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "${{ env.MONGODB_USERNAME }}"
          echo "Job Env"
          echo "${{ env.MONGODB_DB_NAME }}"
